const ADD_NOTE = 'ADD_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const UPDATE_NOTE = 'UPDATE_NOTE';
const NOTES_RECEIVED = 'NOTES_RECEIVED';

export {
  ADD_NOTE,
  DELETE_NOTE,
  UPDATE_NOTE,
  NOTES_RECEIVED,
};
